call plug#begin('~/.vim/plugged')


Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'Chiel92/vim-autoformat'


Plug 'vim-syntastic/syntastic'

"Plug 'scrooloose/nerdtree'
"Plug 'ycm-core/YouCompleteMe'

Plug 'dylanaraps/wal.vim'

call plug#end()

" Use the colorsheme generated by pywal
colorscheme wal


" Vim-airline theme
let g:airline_theme='powerlineish'


" Stuff
set nocompatible
set encoding=utf-8

syntax enable

set shell=/bin/zsh
set number
set colorcolumn=80
set hidden
set hlsearch


" Mappings
imap kl <Esc> 


" Commands
:command C let @/=""



" Syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0


" Open NERDTree with Vim
"autocmd vimenter * NERDTree"

