call plug#begin('~/.vim/plugged')


Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'rust-lang/rust.vim'
Plug 'ycm-core/YouCompleteMe'
Plug 'vim-syntastic/syntastic'

Plug 'scrooloose/nerdtree'

Plug 'dylanaraps/wal.vim'

call plug#end()


" Vim-airline theme
let g:airline_theme='powerlineish'

" Make Rustfmt be run on every save
let g:rustfmt_autosave = 1


" Use the colorsheme generated by pywal
colorscheme wal




set shell=/bin/bash
set number
set colorcolumn=80
set hidden
set hlsearch


" Mappings
map çç :w <Enter> :!clear; cargo run <Enter>
map \\ :YcmCompleter GetDoc <Enter>

imap kl <Esc> 


" Commands
:command C let @/=""



" Syntastic config
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0



" Open NERDTree with Vim
autocmd vimenter * NERDTree
